unified wsi script
handles choice of clipboard source
choice of local or server whisper.cpp

diff --git a/wsi b/wsi
--- a/wsi
+++ b/wsi
@@ -1,5 +1,5 @@
 #!/usr/bin/zsh
-#If you replace the shell above with bash, note also lines 56 to 66
+#If you replace the shell above with bash, note also lines 121 to 124
 # Copyright (c) 2024 Quantius Benignus
 # 
 # THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
@@ -13,73 +13,105 @@
 
 # NAME: wsi 
 # PREREQUSITES: 
-#      - whisper.cpp installation (see https://github.com/ggerganov/whisper.cpp) 
-#      - recent versions of 'sox', 'xsel' (or 'wl-copy' in Wayland) command-line programs from your system's repositories.
+#  - whisper.cpp installation (see https://github.com/ggerganov/whisper.cpp) 
+#  - recent versions of 'sox', 'curl', 'jq', 'xsel' or 'wl-copy' CLI tools from your system's repositories.
 #--------------------------------------------------------------------------
-# Initialize default clipboard value, use PRIMARY selection (middle mouse button to paste transcribed text). 
-CLIPBOARD=false
 
-#--USER CONFIGURATION BLOCK.--------------------------------------------------------------------------- 
+#X11 or Wayland (2nd line may catch edge cases):
+wm="$XDG_SESSION_TYPE"
+#wm="${XDG_SESSION_TYPE:-$(loginctl show-session $(loginctl | grep $(whoami) | awk '{print $1}') -p Type --value)}"
+
+#---USER CONFIGURATION BLOCK----------------------------------------------------------------------
 #Please, adjust the variables here to suit your environment:
-#Override clipboard choice from here instead of using a command line flag ('wsi -c') when calling this script: 
-#(uncomment next line to paste from clipboard with 'CTRL+V' or 'SHIFT+Ins' by default.) 
-#CLIPBOARD=true
-# Store temp files in shared memory for speed and to reduce SSD/HDD "grinding":
+# Store temp files in memory for speed and to reduce SSD/HDD "grinding":
 TEMPD='/dev/shm'
-# Default whisper.cpp model file for inference. PROVIDE CORRECT LOCATION:
-#model="$HOME/AI/Models/whisper/ggml-tiny.en.bin"
-model="$HOME/AI/Models/whisper/ggml-base.en.bin"
+# Default whisper.cpp model file for inference:
+#model="$TEMPD/ggml-base.en.bin"
+model="$HOME/CHANGE_PATH_TO/WHISPER_CPP/MODELS/HERE/ggml-base.en.bin"
 # Hardcoded temp wav file to store the voice memo and get overwritten every time (in RAM):
 ramf="$TEMPD/wfile"
-#Set the number of processing threads for whisper.cpp inference (uncomment and adjust for your case or use optimum below):
-#NTHR=8
+#Set the number of processing threads for whisper.cpp inference (adjust for your case):
+NTHR=8
 #It seems that the optimum number of transcribe threads should equal half CPU processing cores:
-NTHR=$(( $(getconf _NPROCESSORS_ONLN) / 2 ))
-#--END USER CONFIGURATION BLOCK------------------------------------------------------------------------
+#NTHR=$(( $(getconf _NPROCESSORS_ONLN) / 2 ))
+# Use PRIMARY selection (middle mouse button to paste) unless CLIPBOARD selected from GUI: 
+CLIPBOARD=false
+#Provide hardcoded whisper.cpp hostname and port. To be used when invoked with -n option from CLI:
+WHOST="127.0.0.1"
+WPORT="58080"             
+#Can be overwritten from Blurt when command line argument IP:PORT is supplied instead of '-n'
+#---END USER CONFIG BLOCK------------------------------------------------------------------------
 
-
-#X11 or Wayland:
-wm="${XDG_SESSION_TYPE:-$(loginctl show-session $(loginctl | grep $(whoami) | awk '{print $1}') -p Type --value)}"
-
-#--CHECK DEPENDENCIES. This block can be commented out once setup confirmed.---------------------------
+#---CHECK DEPENDENCIES. This block can be commented out once dependencies confirmed-----------------------------------
+command -v curl &>/dev/null || { echo "curl is required. Please, install curl" >&2 ; exit 1 ; }
+#The next is only needed if curl requests json output from the whisper.cpp server;
+#command -v jq &>/dev/null || { echo "jq is required. Please, install jq" >&2 ; exit 1 ; }
 command -v sox &>/dev/null || { echo "sox is required. Please, install sox" >&2 ; exit 1 ; }
 command -v transcribe &>/dev/null || { echo -e "Please, install whisper.cpp (see https://github.com/ggerganov/whisper.cpp)\
 \nand create 'transcribe' in your PATH as a symbolic link to the main executable, e.g.\n \
- 'ln -s /full/path/to/whisper.cpp/main \$HOME/bin/transcribe'" >&2 ; exit 1 ; }
+ 'ln -s /full/path/to/whisper.cpp/main \$HOME/.local/bin/transcribe'" >&2 ; exit 1 ; }
 #Now let's check if we are in X11 or Wayland and use the right utility:
 if [[ wm == "wayland" ]]; then
     command -v wl-copy &>/dev/null || { echo "wl-copy is needed for the clipboard. Please, install wl-copy" >&2 ; exit 1 ; } 
 elif [[ wm == "X11" ]]; then
     command -v xsel &>/dev/null || { echo "We rely on xsel for the clipboard. Please, install xsel." >&2 ; exit 1 ; }
 fi
-#--END CHECK DEPENDENCIES. The above block can be commented out after successful first run.------------
+#This is needed if wsi is used with Blurt (GNOME shell extension):
+gsettings --schemadir /home/u1/.local/share/gnome-shell/extensions/blurt@quantiusbenignus.local/schemas/ get org.gnome.shell.extensions.blurt use-api &> /dev/null || { echo "This \
+ script is made to work with Blurt (GNOME shell extension). Please, install it from https://extensions.gnome.org/extension/6742/blurt/"; exit 1 ; }
+#---END CHECK DEPENDENCIES. The above block can be commented out after successful 1st run----------------------------
 
-# Process command line arguments. (CLIPBOARD can be selected by default from USER CONFIG BLOCK above.)
+#Hear the complaints of the above tools and do not continue with the sequence:
+set -e
+
+# Process command line arguments
 while [ $# -gt 0 ]; do
     case "$1" in
         -c|--clipboard)
             CLIPBOARD=true
             shift
             ;;
-        -h|--help)
+        -n|--netapi)
+            #This uses the hostname or IP and port specified in the config block (when run from CLI or set in Blurt with '-something')
+            #Can be overwritten from Blurt, supplied as command line flag IP:PORT instead of this option
+            IPnPORT="$WHOST:$WPORT" 
+            if [[ "$(curl -s -f -o /dev/null -w '%{http_code}' $IPnPORT)" != "200" ]]; then
+                echo "Can't connect to whisper.cpp server at provided address!" >&2   
+                exit 1
+            fi
+            shift
+            ;;
+        --help)
             echo "Usage: $0 [-c|--clipboard]"
             echo "  -c, --clipboard: Use clipboard instead of PRIMARY selection"
             exit 0
             ;;
         *)
-            echo "Unknown option: $1"
-            exit 1
+            #The network address and port should have already been sanitized in extension
+            IPnPORT=$1
+            if [[ "$(curl -s -f -o /dev/null -w '%{http_code}' $IPnPORT)" != "200" ]]; then
+                echo "Can't connect to a whisper.cpp server at provided address!" >&2   
+                exit 1
+            fi
+            shift
             ;;
     esac
 done
 
-#Hear the complaints and do not continue with the sequence:
-set -e
-
-rec -q -t wav $ramf rate 16k silence 1 0.1 1% 1 2.0 6%  2>/dev/null
+#trap "" SIGINT
+rec -q -t wav $ramf rate 16k silence 1 0.1 1% 1 2.0 5%  2>/dev/null
  
-str="$(transcribe -t $NTHR -nt -m $model -f $ramf 2>/dev/null)" 
-
+if [ -n "$IPnPORT" ]; then
+    str=$(curl -S -s $IPnPORT/inference \
+        -H "Content-Type: multipart/form-data" \
+        -F file="@$ramf" \
+        -F temperature="0.0" \
+        -F temperature_inc="0.2" \
+        -F response_format="text")
+# | jq -r '.text' )
+else
+    str="$(transcribe -t $NTHR -nt -m $model -f $ramf 2>/dev/null)" 
+fi
 # Whisper detected non-speech events such as (wind blowing): 
 str="${str/\(*\)}"   
 str="${str/\[*\]}"
@@ -105,9 +137,7 @@ if [[ -z "${DISPLAY}" ]] || [[ -z "${DESKTOP_SESSION}" ]] || [[ -z "${XDG_CURREN
 #"Not running in a known graphics environment. Using standard output:
     echo $str ; exit 0
 else
- #If the system graphics environment is not GNOME, we can only run this script directly, not from a GNOME extension.
-
- #Now let's check if we are in X11 or Wayland and use the right utility: 
+#xsel or wl-copy:
  case "$wm" in
     "x11")
         if [ "$CLIPBOARD" = true ]; then
